Fixed hot cache update on calls to Set()
groupcache/groupcache-go pull request #11
Opened 2024-12-03 01:26 UTC by thrawn01

### Purpose
@xWiiLLz Reported the hot cache's of remote peers were not updated when calling `Set()`. https://github.com/mailgun/groupcache/pull/69

This PR fixes a long standing TODO where there was some question if the hot cache should always be updated on calls to `Set()`. 

### Resolution
We should ALWAYS update the main cache and delete the key from the hot cache when `Set()` is called.

### Rationale
We do not know when the owning peer may switch to a different node due to cluster topography changes. If an owner belongs to a different node the instant after `Set()` completes, calls to `Get()`, consulting the hot cache, may find the previously set value.

Because we don't know which or when a node in the cluster may become the owner, every node in the cluster should be treated identically.

I left the `hotCache` boolean in the signature of `Set()` as I didn't want to make a version breaking change.

2024-12-25 21:49 UTC, Tochemey approved these changes

2024-12-26 21:22 UTC, Baliedge requested changes
LGTM.  Just a little nit to pick.

2024-12-26 21:22 UTC, Baliedge commented on Makefile
> +	@echo "\033[32mEVERYTHING PASSED!\033[0m"
Color terminals cannot be assumed.

2025-01-02 19:06 UTC, thrawn01 commented on Makefile
> +	@echo "\033[32mEVERYTHING PASSED!\033[0m"
Seems like this might have been true 10+ years ago, The worst that could happen is they get some escape codes in their output. I don't think we should optimize for the odd chance someone is running this on a TSR compatible terminal.

2025-01-02 19:07 UTC, merged